name: Build Proton
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016, macOS-10.14]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup MSBuild.exe
        if: matrix.os == 'windows-2016'
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Dependencies
        run: yarn

      - name: Build
        run: yarn package

      - name: Prepare to Deploy
        id: before_deploy
        shell: bash
        run: |
          rm -rf ./release/*.blockmap
          rm -rf ./release/*.zip
          export NAME=$(ls release/proton-wallet*)
          echo ::set-output name=file_name::${NAME:8}

      - name: Upload to GH Release
        if: github.event_name == 'release' && github.repository == 'turtlecoin/turtle-wallet-proton'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/${{ steps.before_deploy.outputs.file_name }}
          asset_name: ${{ steps.before_deploy.outputs.file_name }}
          asset_content_type: application/octet-stream
